<?php
/**
 * Fullscreen Cheatsheet Popup Template
 *
 * @package CleanerMarketingForms
 * @since 1.0.0
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

// Template configuration
return array(
    'name' => __('Fullscreen Cheatsheet', 'dry-cleaning-forms'),
    'description' => __('A full-screen popup with lead magnet offer for email collection', 'dry-cleaning-forms'),
    'type' => 'fullscreen',
    'category' => 'lead-generation',
    'preview_image' => 'fullscreen-cheatsheet-preview.png',
    'default_settings' => array(
        'popup_type' => 'fullscreen',
        'width' => '100vw',
        'height' => '100vh',
        'position' => 'fixed',
        'overlay' => false,
        'background_color' => 'transparent',
        'background_gradient' => true,
        'gradient_type' => 'linear',
        'gradient_angle' => 135,
        'gradient_color_1' => '#00B4DB',
        'gradient_color_2' => '#0083B0',
        'close_button' => true,
        'close_on_overlay' => false,
        'animation' => 'fadeIn',
        'animation_duration' => 500,
        'padding' => '0',
        'border_radius' => '0'
    ),
    'default_content' => array(
        'custom_html' => true,
        'form_fields' => array(
            array(
                'type' => 'text',
                'name' => 'name',
                'label' => __('Name', 'dry-cleaning-forms'),
                'placeholder' => __('Enter your name here...', 'dry-cleaning-forms'),
                'required' => true,
                'width' => '100',
                'custom_css' => 'dcf-cheatsheet-input'
            ),
            array(
                'type' => 'email',
                'name' => 'email',
                'label' => __('Email', 'dry-cleaning-forms'),
                'placeholder' => __('Enter your email here...', 'dry-cleaning-forms'),
                'required' => true,
                'width' => '100',
                'custom_css' => 'dcf-cheatsheet-input'
            )
        ),
        'form_settings' => array(
            'form_name' => __('Email Cheatsheet Capture', 'dry-cleaning-forms'),
            'form_type' => 'contact',
            'show_labels' => false
        ),
        'submit_button' => array(
            'text' => __('Give Me the Cheatsheet!', 'dry-cleaning-forms'),
            'background_color' => '#00D832',
            'text_color' => '#ffffff',
            'border_radius' => '4px',
            'full_width' => true
        ),
        'content' => '
<style>
/* Fullscreen Cheatsheet Styles */
.dcf-popup-fullscreen {
    padding: 0 !important;
}

.dcf-fullscreen-cheatsheet-wrapper {
    width: 100%;
    height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 40px;
    box-sizing: border-box;
}

.dcf-cheatsheet-container {
    width: 100%;
    max-width: 800px;
    text-align: center;
    color: white;
}

.dcf-cheatsheet-title {
    font-size: 48px;
    font-weight: 800;
    line-height: 1.2;
    margin: 0 0 30px 0;
    text-transform: uppercase;
    letter-spacing: -1px;
    color: white;
}

.dcf-cheatsheet-subtitle {
    font-size: 24px;
    font-weight: 300;
    font-style: italic;
    margin: 0 0 20px 0;
    opacity: 0.95;
    color: white;
}

.dcf-cheatsheet-description {
    font-size: 18px;
    line-height: 1.6;
    margin: 0 0 40px 0;
    opacity: 0.9;
    color: white;
}

.dcf-form-placeholder {
    max-width: 500px;
    margin: 0 auto;
}

/* Style the form generated by form builder */
.dcf-fullscreen-cheatsheet-wrapper .dcf-form,
.dcf-fullscreen-cheatsheet-wrapper form {
    max-width: 100%;
}

.dcf-fullscreen-cheatsheet-wrapper .dcf-form-field,
.dcf-fullscreen-cheatsheet-wrapper .dcf-popup-field {
    margin-bottom: 15px;
}

.dcf-fullscreen-cheatsheet-wrapper input[type="text"],
.dcf-fullscreen-cheatsheet-wrapper input[type="email"] {
    width: 100%;
    padding: 18px 25px;
    border: none;
    border-radius: 4px;
    font-size: 16px;
    background: white;
    color: #333;
    box-sizing: border-box;
}

.dcf-fullscreen-cheatsheet-wrapper input::placeholder {
    color: #999;
}

.dcf-fullscreen-cheatsheet-wrapper button[type="submit"],
.dcf-fullscreen-cheatsheet-wrapper input[type="submit"],
.dcf-fullscreen-cheatsheet-wrapper .dcf-submit-button {
    width: 100%;
    padding: 18px 40px;
    background: #00D832;
    color: white;
    border: none;
    border-radius: 4px;
    font-size: 20px;
    font-weight: 700;
    cursor: pointer;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-top: 10px;
    transition: all 0.3s ease;
}

.dcf-fullscreen-cheatsheet-wrapper button[type="submit"]:hover,
.dcf-fullscreen-cheatsheet-wrapper input[type="submit"]:hover,
.dcf-fullscreen-cheatsheet-wrapper .dcf-submit-button:hover {
    background: #00B82C;
    transform: translateY(-2px);
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
}

/* Hide labels since we use placeholders */
.dcf-fullscreen-cheatsheet-wrapper label {
    display: none;
}

.dcf-privacy-notice {
    margin-top: 20px;
    font-size: 14px;
    opacity: 0.8;
    text-decoration: underline;
    cursor: pointer;
    color: white;
}

.dcf-privacy-notice:hover {
    opacity: 1;
}

/* Responsive */
@media (max-width: 768px) {
    .dcf-cheatsheet-title {
        font-size: 32px;
    }
    
    .dcf-cheatsheet-subtitle {
        font-size: 20px;
    }
    
    .dcf-cheatsheet-description {
        font-size: 16px;
    }
    
    .dcf-fullscreen-cheatsheet-wrapper {
        padding: 20px;
    }
}

/* Animations */
@keyframes slideInUp {
    from {
        opacity: 0;
        transform: translateY(30px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

.dcf-cheatsheet-container > * {
    animation: slideInUp 0.6s ease-out backwards;
}

.dcf-cheatsheet-title {
    animation-delay: 0.1s;
}

.dcf-cheatsheet-subtitle {
    animation-delay: 0.2s;
}

.dcf-cheatsheet-description {
    animation-delay: 0.3s;
}

.dcf-cheatsheet-form {
    animation-delay: 0.4s;
}
</style>

<div class="dcf-fullscreen-cheatsheet-wrapper">
    <div class="dcf-cheatsheet-container">
        <h1 class="dcf-cheatsheet-title">
            HOW TO RUN A SUCCESSFUL<br>
            EMAIL MARKETING CAMPAIGN<br>
            [CHEATSHEET]
        </h1>
        
        <p class="dcf-cheatsheet-subtitle">
            Create high-converting email campaigns EVERY time.
        </p>
        
        <p class="dcf-cheatsheet-description">
            Follow this step-by-step checklist (plus valuable resources)<br>
            to get better results from your email marketing campaigns.
        </p>
        
        <div class="dcf-form-placeholder">
            <!-- Form will be dynamically inserted here -->
            [dcf_form]
        </div>
        
        <p class="dcf-privacy-notice">
            No thanks, my emails already convert like crazy.
        </p>
    </div>
</div>'
    ),
    'trigger_settings' => array(
        'type' => 'time_delay',
        'delay' => 5,
        'show_once_per_session' => true
    ),
    'targeting_settings' => array(
        'pages' => 'all',
        'devices' => array('desktop', 'tablet', 'mobile')
    )
);